# -*- coding: utf-8 -*-
"""#quarentena_dados_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mrIZdaYI2AfMYyQK6cuaxWjBlEdDlLrE

# **quarentena_dados**
"""

print("Hello, world!")

import pandas as pd

"""## Importando tabelas"""

filmes = pd.read_csv("https://raw.githubusercontent.com/efochesatto/quarentena_dados/master/ml-latest-small/movies.csv")
filmes.head()

avaliacoes = pd.read_csv("https://raw.githubusercontent.com/efochesatto/quarentena_dados/master/ml-latest-small/ratings.csv")
avaliacoes.head()

avaliacoes.shape

len(avaliacoes)

"""## Lendo as tabelas"""

avaliacoes.query("movieId==1")

avaliacoes.query("movieId==1").mean()

avaliacoes.query("movieId==2").mean()

"""##Agrupando os filmes"""

avaliacoes.groupby("movieId").mean()
#média das avaliações dos filmes

notas_medias_por_filme = avaliacoes.groupby("movieId")["rating"].mean()
#média das avaliações dos filmes, apenas a coluna da nota

filmes

notas_medias_por_filme

filmes_com_notas = filmes.join(notas_medias_por_filme, on="movieId")
#adicionando a coluna de notas (rating) à tabela filmes

filmes_com_notas

ordenando_melhores = filmes_com_notas.sort_values("rating")
#ordenando os filmes pela coluna de nota, que na ordenação padrão trará do menor para o maior

ordenando_melhores

ordenando_melhores_maior_menor = filmes_com_notas.sort_values("rating", ascending=False)
#ordenando os filmes pela coluna de nota com "ascending=False" que trará ordenação do maior para o menor

ordenando_melhores_maior_menor

melhores15 = filmes_com_notas.sort_values("rating", ascending=False).head(15)
#mostrando os 15 melhores filmes

melhores15

avaliacoes.query("movieId == 1")["rating"].plot(kind="hist")
#selecionando, na tabela avaliações, as notas do filme 1 e apresentando em histograma

avaliacoes.query("movieId == 2")["rating"].plot(kind="hist")
#plotando as notas do segundo filme da lista geral

avaliacoes.query("movieId == 88448")["rating"].plot(kind="hist")
#plotando as notas do primeiro filme dos melhores
#o gráfico mostra que este filme tem média 5, mas teve apenas um voto e este voto foi 5;

avaliacoes.query("movieId == 100556")["rating"].plot(kind="hist")
#plotando as notas do segundo filme dos melhores
#o gráfico mostra que este filme tem média 5, mas teve apenas um voto e este voto foi 5;

